name = "trendtrader-backend"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

main = "src/index.js"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "trendtrader-db"
database_id = "e6199ac8-6af2-4e82-850e-1ac73b1915b9"

[env.production.vars]
NODE_ENV = "production"

[env.development.vars]
NODE_ENV = "development"